### ISSUE TITLE
Unable to do translations updates: scons pot mergePot fails

### ISSUE THREAD

**Issue by feerrenrut** [Nardol/dropbox#1]
When testing https://github.com/nvaccess/mrconfig/pull/33 I find `scons pot mergePot` gives the following error:
```
scons: Reading SConscript files ...
  File "/home/nvdal10n/mr/addons/dropbox/buildVars.py", line 21
    "addon_version" : ,
                      ^
SyntaxError: invalid syntax
```

Translations updates for dropbox addon will be disabled until this is resolved. Please open a new issue on https://github.com/nvaccess/mrconfig/ when you are ready.

**Comment by Nardol** [comment]
I've fixed it and submitted nvaccess/mrconfig#47.
Sorry and thanks.
